[package]
name = "ljumvall_test_utils"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Run test CLI and web crates"
version = "0.2.0"

[dependencies]
lazy_static.workspace = true
rand.workspace = true
regex.workspace = true
